name: main-test.NET6

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: MySQL Setup
      run: |
        docker run --name mysql-db -e MYSQL_ROOT_PASSWORD=root -d -v ${{ github.workspace }}/scripts:/docker-entrypoint-initdb.d mysql:8.0.34
        sleep 20

    - name: Ejecutar el script SQL "install.sql"
      run: |
        docker exec mysql-db mysql -uroot -proot -e "source /docker-entrypoint-initdb.d/install.sql"
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Drop MySQL
      run: |
        docker stop mysql-db
        docker rm mysql-db
